package DBIx::Class::Manual::SQLHackers;

our $VERSION = '1.1';

=head1 NAME

DBIx::Class::Manual::SQLHackers - DBIC for SQLHackers Table of Contents

=over

=item L<Introduction|DBIx::Class::Manual::SQLHackers::Introduction>

=item L<CREATE|DBIx::Class::Manual::SQLHackers::CREATE>

=item L<INSERT|DBIx::Class::Manual::SQLHackers::INSERT>

=item L<SELECT|DBIx::Class::Manual::SQLHackers::SELECT>

=item L<UPDATE|DBIx::Class::Manual::SQLHackers::UPDATE>

=item L<DELETE|DBIx::Class::Manual::SQLHackers::DELETE>

=item L<BEGIN, COMMIT|DBIx::Class::Manual::SQLHackers::Transactions>

=back

=head1 AUTHOR

Jess Robinson <castaway@desert-island.me.uk>, L<http://metacpan.org/author/JROBINSON>

=head1 COPYRIGHT

Copyright (c) 2010 - 2012 the L</AUTHOR>

=head1 LICENSE

This library is free software and may be distributed under the same terms
as perl itself.

=cut
